[package]
name = "danmaku-gui-linux"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "danmaku-gui"
path = "src/main.rs"

[dependencies]
cairo-rs = "0.22.0"
clap = { version = "4.6.1", features = ["derive"] }
gdk4-x11 = { version = "0.11.0", features = ["v4_10"] }
gio = "0.22.6"
glib = "0.22.7"
gtk4 = { version = "0.11.3", features = ["v4_14"] }
pangocairo = "0.22.0"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
x11 = { version = "2.21.0", features = ["xlib"] }

